### PR TITLE
option to suppress startup banner

### PR DESCRIPTION
**Pull request by bodawei**
This is a proposal of a solution to https://github.com/electrode-io/electrode-server/issues/23

### Problem
When running lots of integration-type tests using the electrode server, we end up with a lot of "noise" in our logs with the "Hapi.js server running" message that gets printed automatically.

### Proposed Solution
This adds an optional configuration value:
```
electrode: {
  suppressStartupBanner: true
}
```
which, if set to true, will cause Electrode Server to not display its startup banner.

This includes the code change, a doc change, and a test to validate it works.

### CODE REVIEW

**Comment by jchip** [comment]
I prefer something more generic than a specific option like `suppressStartupBanner` though.
For example, maybe name it `verbose`.  It could be a boolean or even a level (numeric or label like `info`, `warn`, `error`).

Internally we have a dedicate module that's like a slightly more glorified `console` that allows setting an env level to suppress any kind of information logs from our modules.

**Comment by bodawei** [comment]
That sounds reasonable.  I'm inclined to do the following, then:

1. change the configuration to property name to logLevel
2. Create a simple type called something like logger, which has three methods: info(), warn(), error(). electrode-server.js would instantiate one with the setting from logLevel.  the logger instance would just turn around and call console.log|warn|error, but only if the function is >= logLevel (thus, if logLevel is 'warn', and error() is called, it would print, but info() would not)
3. replace all calls to console.*() with logger.*().

Other thoughts:
* @jchip I'm not sure how this would or would not fit with your internal more glorified system. Thoughts?
* I'm inclined to leave the property in the electrode object in the config, but I could see an argument for promoting it in some way and offering it as something all plugins could look for and live off of, thus allowing any plugin to look at this level and decide whether to print.

**Comment by jchip** [comment]
@bodawei sounds good.

**Comment by bodawei** [comment]
Snafu'ed this. Replaced with: https://github.com/electrode-io/electrode-server/pull/27

**Pull request closed without merging**
